theme = "yo_berry_dark"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["file-encoding", "file-line-ending", "file-type"]
separator = "|"

[editor.indent-guides]
render = true

[editor.lsp]
enable = false
